<a href="https://colab.research.google.com/github/raphaeldiscky/ml-projects/blob/main/classification%20-%20two%20classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('citrus.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [2]:
# show dataframe
df.head(10000)

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [3]:
# change orange and grapefruit to numeric
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
# convert dataframe to numpy array
dataset = df.values

In [5]:
print(dataset)

[[0 2.96 86.76 172 85 2]
 [0 3.91 88.05 166 78 3]
 [0 4.42 95.17 156 81 2]
 ...
 [1 15.59 256.5 168 82 20]
 [1 15.92 260.14 142 72 11]
 [1 16.45 261.51 152 74 2]]


In [6]:
X = dataset[:,1:6] # last 4 column is attributes
y = dataset[:,0] # first column is label

In [7]:
# normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [8]:
# split data training and testing, use 30% from all data for testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [9]:
import numpy as np

# change column value from numeric to float32  
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [10]:
# build model

from keras.models import Sequential
from keras.layers import Dense

# create architecture for ANN
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])

In [11]:
# optimizer and loss function
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])


In [12]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 13s 1ms/step - loss: 0.6662 - accuracy: 0.6233
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5899 - accuracy: 0.8992
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.9201
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3921 - accuracy: 0.9270
Epoch 5/100
219/219 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.9319
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2680 - accuracy: 0.9208
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2360 - accuracy: 0.9224
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2075 - accuracy: 0.9301
Epoch 9/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2049 - accuracy: 0.9260
Epoch 10/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2008 - accur

In [13]:
# evaluate to check if model underfit or overfit
model.evaluate(X_test, Y_test)

94/94 [==============================] - 1s 947us/step - loss: 0.1754 - accuracy: 0.9260


[0.1753937005996704, 0.9259999990463257]